services:
  recherche-entreprises-db:
    container_name: recherche-entreprises
    platform: linux/amd64 #for platform error on Apple M1 chips
    env_file: .env
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - recherche-entreprises:/var/lib/postgresql/data/ #using a volume
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  webdb:
    image: webdb/app
    ports:
      - 22071:22071
    environment:
      SCAN_HOSTS: recherche-entreprises-db
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@recherche-entreprises-db:5432/${DATABASE_NAME}?schema=umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${UMAMI_APP_SECRET}
    depends_on:
      - recherche-entreprises-db

volumes:
  recherche-entreprises: